gripper_open = 0.35
gripper_close = 0.55
gripper_speed = 1.0
gripper_max_effort = 50.0

[home]
joints = [-0.457496, 0.997315, 1.136637, -3.102863, -1.300773, -1.577962]
time_from_start = 5.0
carriage = 12.5500
lift = 0.5000