gripper_open = 0.35
gripper_close = 0.55
gripper_speed = 1.0
gripper_max_effort = 50.0
lift_position = 0.2590450942516327
carriage_position = 12.550000190734863

[home]
joints = [-0.344518, 1.396093, 1.669235, 3.110204, -1.427716, -1.557667]
time_from_start = 5.0
lift = 0.2590450942516327
carriage = 12.550000190734863

[pre_storage1-1]
joints = [0.542313, 1.107508, 0.910720, 2.273500, -1.003185, -1.769362]
time_from_start = 3.0

[storage1-1]
joints = [0.641163, 1.034272, 0.789634, 2.319210, -0.978090, -1.827030]
time_from_start = 3.0

[proposal1-1]
joints = [-0.197969, 0.856364, 0.942797, 2.993955, -0.929272, -1.558572]
time_from_start = 3.0

[proposal2-1]
joints = [-0.198009, 0.727259, 0.999784, 2.966011, -0.820248, -1.558980]
time_from_start = 3.0

[storage1-2]
joints = [0.419716, 0.941583, 0.845918, 2.369660, -1.009901, -1.640683]
time_from_start = 3.0

[storage1-3]
joints = [0.253627, 0.956464, 0.962721, 2.578967, -0.935166, -1.579833]
time_from_start = 3.0

[storage2-3]
joints = [0.328365, 0.792888, 0.914303, 2.350801, -0.979665, -1.464427]
time_from_start = 3.0

[storage2-2]
joints = [0.508800, 0.817289, 0.730214, 2.275891, -1.100061, -1.629628]
time_from_start = 3.0

[storage2-1]
joints = [0.741257, 0.878340, 0.636960, 2.138756, -1.059193, -1.763380]
time_from_start = 3.0

[proposal1-2]
joints = [-0.514075, 0.675149, 0.464941, -2.989604, -1.365774, -1.564818]
time_from_start = 3.0

[proposal2-2]
joints = [-0.722751, 0.812602, 1.191655, -2.667008, -0.641509, -1.826989]
time_from_start = 10.0

[proposal2-3]
joints = [-1.362178, 0.969863, 1.317262, -1.895092, -0.734091, -2.004811]
time_from_start = 10.0

[proposal1-3]
joints = [-0.871837, 0.683311, 0.441000, -2.644993, -1.340014, -1.472261]
time_from_start = 3.0

[accepted1-1]
joints = [-1.337253, 0.808536, 0.246370, -2.417324, -1.323756, -1.171902]
time_from_start = 3.0

[accepted1-2]
joints = [-1.469197, 0.883963, 0.244447, -2.310846, -1.197120, -0.979065]
time_from_start = 3.0

[accepted2-1]
joints = [-1.469334, 0.734990, 0.276926, -2.202494, -1.301932, -1.194165]
time_from_start = 3.0

[accepted2-2]
joints = [-1.651140, 0.860334, 0.275296, -2.190489, -1.132356, -0.973299]
time_from_start = 3.0

[pre_storage2-1]
joints = [0.819848, 1.134742, 0.966565, 2.126724, -1.052778, -1.728098]
time_from_start = 3.0

[pre_storage2-2]
joints = [0.734007, 1.034958, 1.148274, 1.977824, -0.985868, -1.445161]
time_from_start = 3.0

[pre_storage1-2]
joints = [0.457780, 1.106339, 1.124062, 2.284861, -0.922551, -1.541237]
time_from_start = 3.0

[pre_storage1-3]
joints = [0.080200, 0.964898, 0.958863, 2.640256, -1.077661, -1.605387]
time_from_start = 3.0

[pre_storage2-3]
joints = [0.248143, 0.885118, 1.054360, 2.405225, -1.026154, -1.392465]
time_from_start = 3.0

[pre_proposal1-1]
joints = [-0.226022, 1.059365, 1.256600, 3.050756, -0.808332, -1.556969]
time_from_start = 3.0

[test]
joints = [0.596959, 1.157299, 0.916864, 2.324942, -1.063244, -1.818480]
time_from_start = 3.0

[test2]
joints = [-0.344521, 1.396008, 1.669201, 3.110179, -1.427652, -1.557684]
time_from_start = 3.0

[circle]
joints = [-0.344538, 1.395999, 1.669174, 3.110206, -1.427654, -1.557681]
time_from_start = 3.0

[circle1]
joints = [0.596976, 1.157135, 0.916847, 2.324921, -1.063178, -1.818475]
time_from_start = 3.0

[test1]
joints = [-0.344520, 1.396007, 1.669201, 3.110178, -1.427651, -1.557683]
time_from_start = 3.0

[pre_storage3-1]
joints = [1.077345, 1.087356, 1.193520, 1.535107, -0.972517, -1.431221]
time_from_start = 3.0

[pre_storage3-2]
joints = [0.898516, 0.853793, 0.979222, 1.793814, -1.120928, -1.377289]
time_from_start = 3.0

[pre_storage3-3]
joints = [0.871621, 0.918400, 1.470289, 1.477901, -0.969594, -0.879579]
time_from_start = 3.0

[pre_storage4-1]
joints = [1.384051, 1.118890, 1.173732, 1.327379, -0.945538, -1.417671]
time_from_start = 3.0

[pre_storage4-2]
joints = [1.384063, 1.002073, 1.286208, 1.215409, -1.127985, -1.282701]
time_from_start = 3.0

[pre_storage4-3]
joints = [1.384350, 0.830187, 1.270640, 1.189962, -1.252495, -1.103874]
time_from_start = 3.0

[pre_storage5-1]
joints = [1.696282, 1.103289, 0.970934, 1.168227, -0.893918, -1.705702]
time_from_start = 3.0

[pre_storage5-2]
joints = [1.741930, 1.002523, 1.041780, 1.066854, -1.073938, -1.514526]
time_from_start = 3.0

[pre_storage5-3]
joints = [1.906752, 0.962747, 1.204402, 0.873408, -1.245513, -1.438977]
time_from_start = 3.0

[pre_storage6-1]
joints = [1.924433, 1.068988, 0.779073, 0.928464, -0.951685, -1.855452]
time_from_start = 10.0

[pre_storage6-2]
joints = [2.066198, 1.019158, 0.862788, 0.794908, -0.934654, -1.700120]
time_from_start = 3.0

[pre_storage6-3]
joints = [2.194799, 1.013228, 0.999792, 0.675005, -1.065808, -1.601941]
time_from_start = 3.0

[pre_proposal1-2]
joints = [-0.513965, 0.674876, 0.465055, -2.974563, -1.533272, -1.564599]
time_from_start = 10.0

[pre_proposal1-3]
joints = [-0.885324, 0.727164, 0.440976, -2.658480, -1.559403, -1.472122]
time_from_start = 10.0

[pre_proposal2-1]
joints = [-0.198008, 0.741940, 1.017816, 2.966006, -1.165284, -1.558407]
time_from_start = 10.0

[pre_proposal2-2]
joints = [-0.722746, 0.812450, 1.212589, -2.666924, -0.959110, -1.826736]
time_from_start = 10.0

[pre_proposal2-3]
joints = [-1.362186, 0.969722, 1.316884, -1.963667, -0.918554, -2.004640]
time_from_start = 10.0

[pre_accepted1-1]
joints = [-1.337280, 0.844566, 0.246538, -2.301147, -1.631971, -1.171600]
time_from_start = 10.0

[pre_accepted1-2]
joints = [-1.469231, 0.994540, 0.244607, -2.301195, -1.505605, -0.979054]
time_from_start = 10.0

[pre_accepted1-3]
joints = [1.351544, -0.575020, 0.906099, 0.424620, -1.479327, -0.208217]
time_from_start = 3.0

[pre_accepted2-1]
joints = [-1.469296, 0.794219, 0.277010, -2.188770, -1.584938, -1.194085]
time_from_start = 10.0

[pre_accepted2-2]
joints = [-1.651120, 0.904731, 0.275611, -2.047680, -1.441912, -0.973171]
time_from_start = 10.0

[pre_accepted2-3]
joints = [1.343071, -0.584673, 0.693503, 0.777111, -1.352389, -0.295859]
time_from_start = 3.0

[pre_proposal3-1]
joints = [-0.349538, 0.682888, 1.538649, 2.785689, -0.292681, -1.163963]
time_from_start = 10.0

[pre_proposal3-2]
joints = [-0.162815, 0.668393, 1.610532, 2.801771, -0.106926, -1.165806]
time_from_start = 10.0

[pre_proposal3-3]
joints = [-0.344582, 0.513884, 1.371351, -2.163633, -0.648351, -2.253721]
time_from_start = 10.0

[pre_proposal4-1]
joints = [-0.354298, 0.432571, 1.322145, 2.954101, -0.383493, -1.378867]
time_from_start = 10.0

[pre_proposal4-2]
joints = [-0.200552, 0.426104, 1.298647, 3.103319, -0.362086, -1.435836]
time_from_start = 10.0

[pre_proposal4-3]
joints = [0.077367, 0.300118, 1.323426, 2.889723, -0.191264, -1.234290]
time_from_start = 10.0

[pre_proposal5-1]
joints = [-0.374666, 0.195241, 0.906545, 3.108011, -0.644523, -1.543032]
time_from_start = 3.0

[pre_proposal5-2]
joints = [-0.224438, 0.199960, 1.113266, 3.123048, -0.308426, -1.609524]
time_from_start = 3.0

[pre_proposal5-3]
joints = [-0.044864, 0.131000, 1.004740, 3.138240, -0.422503, -1.610608]
time_from_start = 3.0

[pre_proposal6-1]
joints = [-0.408287, 0.023241, 0.957819, -3.083445, -0.327045, -1.587754]
time_from_start = 3.0

[pre_proposal6-2]
joints = [-0.283730, 0.023385, 0.957827, -3.083638, -0.332223, -1.588082]
time_from_start = 3.0

[pre_proposal6-3]
joints = [-0.082904, -0.063558, 0.853452, -3.085301, -0.357693, -1.586008]
time_from_start = 3.0

[pre_accepted3-1]
joints = [-1.878662, 0.923931, 0.876589, -1.532778, -1.384544, -1.634097]
time_from_start = 10.0

[pre_accepted3-2]
joints = [-1.980161, 1.119157, 0.656503, -1.825772, -1.107955, -1.098523]
time_from_start = 10.0

[pre_accepted3-3]
joints = [-1.985046, 1.115740, 0.656165, -1.672694, -0.808899, -1.098168]
time_from_start = 3.0

[pre_accepted4-1]
joints = [-2.104577, 0.981592, 0.740155, -1.567744, -1.059296, -1.294782]
time_from_start = 3.0

[pre_accepted4-2]
joints = [-2.126791, 1.029208, 0.589551, -1.631634, -0.924844, -1.116607]
time_from_start = 3.0

[pre_accepted4-3]
joints = [-2.199356, 1.051890, 0.482505, -1.620935, -0.692768, -1.006641]
time_from_start = 3.0

[pre_accepted5-1]
joints = [-2.394113, 0.842698, 0.523809, -1.155520, -1.076670, -1.268097]
time_from_start = 3.0

[pre_accepted5-2]
joints = [-2.374471, 0.953990, 0.498374, -1.182402, -0.847941, -1.130646]
time_from_start = 3.0

[pre_accepted5-3]
joints = [-2.455998, 0.966088, 0.536518, -0.710103, -0.731919, -1.479030]
time_from_start = 3.0

[pre_accepted6-1]
joints = [-2.650115, 0.999625, 0.516649, -1.111956, -0.751240, -1.125810]
time_from_start = 3.0

[pre_accepted6-2]
joints = [-2.637126, 1.087030, 0.487560, -1.159163, -0.473074, -1.094238]
time_from_start = 3.0

[pre_accepted6-3]
joints = [-2.687789, 1.000944, 0.270320, -0.980518, -0.151157, -0.874744]
time_from_start = 3.0

[storage3-1]
joints = [-2.087054, -0.161047, 0.693759, 1.924049, 1.352740, 0.722340]
time_from_start = 3.0

[storage3-2]
joints = [-2.087090, -0.096159, 0.693679, 1.945226, 1.458545, 0.738632]
time_from_start = 3.0

[storage3-3]
joints = [0.827484, 0.686038, 0.941319, 1.801299, -1.084352, -1.240738]
time_from_start = 3.0

[storage4-1]
joints = [1.542439, 0.642889, 0.600518, 0.995545, -1.196436, -1.567971]
time_from_start = 3.0

[storage4-2]
joints = [1.542437, 0.575633, 0.610789, 1.093643, -1.272513, -1.550190]
time_from_start = 3.0

[storage4-3]
joints = [1.542546, 0.526150, 0.652070, 1.186951, -1.309473, -1.443617]
time_from_start = 3.0

[storage5-1]
joints = [1.646712, 0.703381, 0.484643, 1.052175, -0.983736, -1.707429]
time_from_start = 3.0

[storage5-2]
joints = [1.711039, 0.662882, 0.453632, 1.197832, -1.075611, -1.825708]
time_from_start = 3.0

[storage5-3]
joints = [1.774882, 0.549964, 0.460386, 1.071205, -1.176733, -1.574405]
time_from_start = 3.0

[storage6-1]
joints = [2.026077, 1.065579, 0.667100, 1.004472, -0.494773, -2.033644]
time_from_start = 10.0

[storage6-2]
joints = [2.059810, 0.679866, 0.366924, 0.752620, -0.899976, -1.751208]
time_from_start = 3.0

[storage6-3]
joints = [2.124315, 0.653286, 0.359445, 0.884229, -0.973519, -1.788540]
time_from_start = 3.0

[proposal3-1]
joints = [-0.359639, 0.635904, 1.459132, 2.682996, -0.176059, -1.213017]
time_from_start = 10.0

[proposal3-2]
joints = [-0.162959, 0.606562, 1.520484, 2.801862, 0.098304, -1.167111]
time_from_start = 3.0

[proposal3-3]
joints = [-0.344571, 0.513999, 1.172308, -2.097521, -0.594207, -2.254364]
time_from_start = 3.0

[proposal4-1]
joints = [-0.388259, 0.432470, 1.347051, 2.973930, -0.042836, -1.379698]
time_from_start = 3.0

[proposal4-2]
joints = [-0.214474, 0.425787, 1.417656, 3.101022, 0.112189, -1.437722]
time_from_start = 3.0

[proposal4-3]
joints = [0.028706, 0.299927, 1.339124, 2.880741, 0.093843, -1.235668]
time_from_start = 3.0

[proposal5-1]
joints = [-0.370325, 0.159712, 1.186887, 3.107306, 0.018132, -1.494770]
time_from_start = 3.0

[proposal5-2]
joints = [-0.201851, 0.116346, 0.896522, 3.134393, -0.391929, -1.565548]
time_from_start = 3.0

[proposal5-3]
joints = [-0.079512, 0.042004, 0.898297, -2.753695, -0.299454, -1.889253]
time_from_start = 3.0

[proposal6-1]
joints = [-0.388410, -0.070039, 0.745971, 3.011624, -0.315254, -1.449345]
time_from_start = 3.0

[proposal6-2]
joints = [-0.238539, -0.051594, 1.003587, -3.139788, 0.082832, -1.486025]
time_from_start = 3.0

[proposal6-3]
joints = [-0.056012, -0.128242, 0.894332, -3.024872, 0.027111, -1.678979]
time_from_start = 3.0

[accepted3-1]
joints = [-1.878639, 0.924393, 0.876585, -1.532764, -1.000830, -1.634086]
time_from_start = 10.0

[accepted3-2]
joints = [-2.036937, 1.045238, 0.656602, -1.764613, -0.856208, -1.122598]
time_from_start = 10.0

[accepted4-1]
joints = [0.413848, 0.007964, 0.732309, 3.098087, -0.483933, -1.558667]
time_from_start = 3.0

[accepted4-2]
joints = [0.511886, -0.156630, 0.852836, -3.090970, -0.036545, -1.699619]
time_from_start = 3.0

[accepted5-1]
joints = [0.287446, -0.157219, 0.852841, -3.090962, -0.065135, -1.699220]
time_from_start = 3.0

[accepted5-2]
joints = [0.386827, -0.373288, 0.795446, -3.086170, 0.327132, -1.697880]
time_from_start = 3.0

[accepted6-1]
joints = [0.208226, -0.385414, 0.777898, -3.085806, 0.326673, -1.696801]
time_from_start = 3.0

[accepted6-2]
joints = [0.312351, -0.535685, 0.494048, -3.085835, 0.150220, -1.694638]
time_from_start = 3.0