gripper_open = 0.35
gripper_close = 0.55

[pre_pick]
joints = [-1.142882, -1.219199, -1.345714, 0.989958, -1.410006, -1.670422]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[pick]
joints = [-1.346116, -0.981415, -1.057587, 1.319914, -1.072331, -1.693212]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[home]
joints = [0.002231, -1.216090, -1.385489, -0.065738, -1.383703, -1.551807]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[pre_place]
joints = [0.502034, -1.151201, -1.656260, -0.578052, -1.154697, -1.224507]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[place]
joints = [0.502002, -0.745842, -1.318265, -1.271452, -0.845231, -0.921659]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[test01]
joints = [-0.231941, -0.461522, -1.405688, -0.520736, -0.697799, -1.166368]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[test02]
joints = [0.095259, -0.970232, -1.906356, -0.220709, -0.375456, -1.524704]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000
