gripper_open = 0.35
gripper_close = 0.55
gripper_speed = 1.0
gripper_max_effort = 50.0

[pre_pick]
joints = [-1.142882, -1.219199, -1.345714, 0.989958, -1.410006, -1.670422]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[pick]
joints = [-1.346116, -0.981415, -1.057587, 1.319914, -1.072331, -1.693212]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[home]
joints = [0.002231, -1.216090, -1.385489, -0.065738, -1.383703, -1.551807]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[pre_place]
joints = [0.502034, -1.151201, -1.656260, -0.578052, -1.154697, -1.224507]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[place]
joints = [0.502002, -0.745842, -1.318265, -1.271452, -0.845231, -0.921659]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[test01]
joints = [-0.231941, -0.461522, -1.405688, -0.520736, -0.697799, -1.166368]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[test02]
joints = [0.095259, -0.970232, -1.906356, -0.220709, -0.375456, -1.524704]
time_from_start = 3.0
carriage = 0.1000
lift = 0.4000

[storage1]
joints = [-0.652302, -1.139049, -0.528110, 0.322478, -1.227391, -1.230121]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[pre_storage1]
joints = [-0.644794, -1.210642, -0.528061, 0.321004, -1.383806, -1.230277]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[pre_storage2]
joints = [-0.466517, -1.138647, -0.528783, 0.269823, -1.447371, -1.291584]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[storage2]
joints = [-0.482444, -1.018935, -0.392565, 0.263707, -1.385608, -1.291519]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[pre_storage3]
joints = [-0.286352, -1.034883, -0.392620, 0.169942, -1.596265, -1.384137]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[storage3]
joints = [-0.286426, -0.996650, -0.392638, 0.160880, -1.424917, -1.391684]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[pre_storage4]
joints = [-0.102407, -1.032585, -0.392708, 0.038152, -1.602776, -1.562891]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[storage4]
joints = [-0.102482, -0.991962, -0.392726, 0.037969, -1.476417, -1.562255]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[proposal1]
joints = [-0.103227, -1.046369, -1.322781, 0.027353, -0.667747, -1.562512]
time_from_start = 1.0
carriage = 0.1000
lift = 0.4000

[pre_proposal1]
joints = [-0.107922, -1.187811, -1.493970, 0.064967, -0.784137, -1.562460]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[pre_proposal2]
joints = [-0.419198, -1.217020, -1.555301, 0.609747, -0.605621, -1.753026]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[pre_proposal3]
joints = [-0.278634, -1.045694, -1.666270, 0.465960, -0.403586, -1.833784]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[pre_proposal4]
joints = [-0.658765, -1.086610, -1.622347, 1.072311, -0.651195, -2.160870]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[proposal4]
joints = [-0.669425, -0.960279, -1.401955, 0.961623, -0.680905, -1.968915]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[proposal3]
joints = [-0.192295, -0.916924, -1.425229, 0.219499, -0.487901, -1.637765]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000

[proposal2]
joints = [-0.450348, -1.007128, -1.200344, 0.513779, -0.834140, -1.674358]
time_from_start = 2.0
carriage = 0.1000
lift = 0.4000
